In [4]:
# Initial imports.
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report,balanced_accuracy_score
from imblearn.metrics import classification_report_imbalanced

In [5]:
global_data_df = pd.read_csv('global_health_data.csv')
global_data_df

FileNotFoundError: [Errno 2] No such file or directory: 'global_health_data.csv'

In [3]:
mean=global_data_df["both_sex_life_exp"].mean()
stdev=global_data_df["both_sex_life_exp"].std()
print(mean)
print(stdev)
print(f"Use {round(mean+stdev,1)} years as the threshold for the high_life_exp group")
print(f"Use {round(mean-stdev,1)} years as the threshold for the low_life_exp group")

NameError: name 'global_data_df' is not defined

In [4]:
# drop the country_code and country columns from the data set
global_data=global_data_df.drop(columns=["country_code","country","fem_life_exp","male_life_exp"])

In [5]:
# create a new column called life_expenctancy_group
bins = [0, 64.3, 79.4, 100]
labels = ['low', 'medium', 'high']
global_data['life_exp_group'] = pd.cut(global_data['both_sex_life_exp'], bins=bins, labels=labels)
global_data['life_exp_encoded'] = pd.cut(global_data['both_sex_life_exp'], bins=bins, labels=[0, 1, 2], include_lowest=True)
global_data

,co,no,no2,o3,so2,pm2_5,pm10,gdp_per_capita,Mean BMI,che_per_capita_usd,both_sex_life_exp,poverty_rate,life_exp_group,life_exp_encoded
0,1350.724521,0.683179,12.363946,79.251521,0.759946,17.227616,42.560698,2057.0,21.255135,6680.0,62.430,54.5,low,0
1,257.109347,0.362959,6.039690,71.634025,1.989154,10.260962,14.133179,12783.0,25.164619,1867.0,77.920,14.3,medium,1
2,241.442119,3.336000,13.501865,69.168845,2.798434,12.425665,37.320633,11683.0,23.912552,2646.0,76.835,5.5,medium,1
3,471.672875,0.718363,5.120278,29.608070,3.372409,18.544950,29.713428,7304.0,21.195410,3878.0,62.390,32.3,low,0
4,423.765962,8.538443,11.451818,29.216860,5.575630,7.109720,9.720282,23107.0,25.974045,2981.0,76.375,35.5,medium,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,273.726837,4.314358,12.812164,60.219622,1.456380,8.780014,19.103754,6867.0,24.569494,6001.0,72.230,14.1,medium,1
145,199.313946,0.010838,0.226337,21.590267,0.407213,2.023984,4.395204,3040.0,24.908416,3745.0,64.975,12.7,medium,1
146,869.873588,6.159495,18.272751,40.186948,15.109423,43.126799,52.487995,7198.0,19.753949,1190.0,73.450,6.7,medium,1
147,526.302397,0.261384,1.657479,18.503096,5.618650,7.969808,11.588515,3478.0,21.281939,5094.0,61.475,54.4,low,0
148,317.144957,0.565041,2.198224,23.643942,2.433017,23.106326,25.703272,3747.0,23.079916,3593.0,59.580,38.3,low,0

In [6]:
global_data = global_data.dropna()
global_data

,co,no,no2,o3,so2,pm2_5,pm10,gdp_per_capita,Mean BMI,che_per_capita_usd,both_sex_life_exp,poverty_rate,life_exp_group,life_exp_encoded
0,1350.724521,0.683179,12.363946,79.251521,0.759946,17.227616,42.560698,2057.0,21.255135,6680.0,62.430,54.5,low,0
1,257.109347,0.362959,6.039690,71.634025,1.989154,10.260962,14.133179,12783.0,25.164619,1867.0,77.920,14.3,medium,1
2,241.442119,3.336000,13.501865,69.168845,2.798434,12.425665,37.320633,11683.0,23.912552,2646.0,76.835,5.5,medium,1
3,471.672875,0.718363,5.120278,29.608070,3.372409,18.544950,29.713428,7304.0,21.195410,3878.0,62.390,32.3,low,0
4,423.765962,8.538443,11.451818,29.216860,5.575630,7.109720,9.720282,23107.0,25.974045,2981.0,76.375,35.5,medium,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,273.726837,4.314358,12.812164,60.219622,1.456380,8.780014,19.103754,6867.0,24.569494,6001.0,72.230,14.1,medium,1
145,199.313946,0.010838,0.226337,21.590267,0.407213,2.023984,4.395204,3040.0,24.908416,3745.0,64.975,12.7,medium,1
146,869.873588,6.159495,18.272751,40.186948,15.109423,43.126799,52.487995,7198.0,19.753949,1190.0,73.450,6.7,medium,1
147,526.302397,0.261384,1.657479,18.503096,5.618650,7.969808,11.588515,3478.0,21.281939,5094.0,61.475,54.4,low,0
148,317.144957,0.565041,2.198224,23.643942,2.433017,23.106326,25.703272,3747.0,23.079916,3593.0,59.580,38.3,low,0

In [7]:
X = global_data.drop(columns=["both_sex_life_exp","life_exp_group","life_exp_encoded"])
X

,co,no,no2,o3,so2,pm2_5,pm10,gdp_per_capita,Mean BMI,che_per_capita_usd,poverty_rate
0,1350.724521,0.683179,12.363946,79.251521,0.759946,17.227616,42.560698,2057.0,21.255135,6680.0,54.5
1,257.109347,0.362959,6.039690,71.634025,1.989154,10.260962,14.133179,12783.0,25.164619,1867.0,14.3
2,241.442119,3.336000,13.501865,69.168845,2.798434,12.425665,37.320633,11683.0,23.912552,2646.0,5.5
3,471.672875,0.718363,5.120278,29.608070,3.372409,18.544950,29.713428,7304.0,21.195410,3878.0,32.3
4,423.765962,8.538443,11.451818,29.216860,5.575630,7.109720,9.720282,23107.0,25.974045,2981.0,35.5
...,...,...,...,...,...,...,...,...,...,...,...
144,273.726837,4.314358,12.812164,60.219622,1.456380,8.780014,19.103754,6867.0,24.569494,6001.0,14.1
145,199.313946,0.010838,0.226337,21.590267,0.407213,2.023984,4.395204,3040.0,24.908416,3745.0,12.7
146,869.873588,6.159495,18.272751,40.186948,15.109423,43.126799,52.487995,7198.0,19.753949,1190.0,6.7
147,526.302397,0.261384,1.657479,18.503096,5.618650,7.969808,11.588515,3478.0,21.281939,5094.0,54.4
148,317.144957,0.565041,2.198224,23.643942,2.433017,23.106326,25.703272,3747.0,23.079916,3593.0,38.3

In [8]:
y = global_data["life_exp_encoded"]
y_1 = global_data["both_sex_life_exp"]

In [9]:
# Splitting into Train and Test sets.
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [10]:
# Try to do StandardScaler later in this same cell.
# Creating a StandardScaler instance.
scaler = StandardScaler() # use this for StandardScaler scaling
#minmaxscaler = MinMaxScaler()
# Fitting the Standard Scaler with the training data.
X_scaler = scaler.fit(X_train) # standardscaler
# X_minmaxscaler = minmaxscaler.fit(X_train)
# Scaling the data.
## For StandardScaler scaling, sub X_minmaxscaler for X_scaler
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [11]:
# Create a random forest regressor.
from sklearn.linear_model import LogisticRegression
#rf_model = RandomForestRegressor(n_estimators = 1024, random_state = 76)
model = LogisticRegression(solver = 'lbfgs',random_state=1)

In [12]:
# Fitting the model
#rf_model = rf_model.fit(X_train_scaled, y_train)
model = model.fit(X_train_scaled, y_train)

In [13]:
# Making predictions using the testing data.
y_pred = model.predict(X_test_scaled)

In [14]:
# Print the accuracy score for the training and testing data for the LogisticRegression ML model
print(model.score(X_train_scaled, y_train))
print(model.score(X_test_scaled, y_test))

0.8378378378378378
0.8421052631578947

In [15]:
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.8882783882783882

In [16]:
cm = confusion_matrix(y_test,y_pred)
cm

array([[ 6,  1,  0],
       [ 5, 21,  0],
       [ 0,  0,  5]])

In [17]:
# Classification report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.55      0.86      0.67         7
           1       0.95      0.81      0.88        26
           2       1.00      1.00      1.00         5

    accuracy                           0.84        38
   macro avg       0.83      0.89      0.85        38
weighted avg       0.89      0.84      0.85        38

In [18]:
# Predicting Continous Data
# Splitting into Train and Test sets. Specifically uses y_1 as the original values for life expectancy (continuous)
X_train, X_test, y_train, y_test = train_test_split(X, y_1, random_state=78)

In [19]:
# Create a random forest regressor.
rf_model = DecisionTreeRegressor(n_estimators = 1024, random_state = 76)
rf_model = rf_model.fit(X_train_scaled, y_train)
y_pred = rf_model.predict(X_test_scaled)

In [20]:
# Print the accuracy score for training and testing data for the RandomForestRegressor
print(rf_model.score(X_train_scaled, y_train))
print(rf_model.score(X_test_scaled, y_test))

0.9633848761034242
0.8396570526195067

In [21]:
# Next step is look for correlations in the data
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from scipy.stats import pearsonr
from sklearn.linear_model import LinearRegression
linearregression_model = LinearRegression()
linearregression_model.fit(X, y_1)

# Use our model to predict a value
predicted = linearregression_model.predict(X)

mse = mean_squared_error(y_1, predicted)
r2 = r2_score(y_1, predicted)

print(f"mean squared error (MSE): {mse}")
print(f"R-squared (R2 ): {r2}")

mean squared error (MSE): 14.047428153301727
R-squared (R2 ): 0.7508472573205696

In [22]:
# compute the correlation coefficients
correlations = []
for i in range(X.shape[1]):
    corr, _ = pearsonr(X.iloc[:,i], y_1)
    correlations.append(corr)

# print the correlation coefficients
print("Correlations: ", correlations)

Correlations:  [-0.043598388271785186, 0.19631244058811406, 0.3954005158315552, 0.5053745264827255, 0.16519834525092425, -0.2480555764302058, -0.32901250079359823, 0.734343188281058, 0.5600079418965207, 0.11075022358879706, -0.6845796928957699]

In [23]:
correlations_data = global_data.drop(columns=["both_sex_life_exp","life_exp_group","life_exp_encoded"])
correlations_data
cols = [x for x in correlations_data.columns]


data = {'features': cols, 'r_values': correlations}

correlations_df=pd.DataFrame(data)
correlations_df

              features  r_values
0                   co -0.043598
1                   no  0.196312
2                  no2  0.395401
3                   o3  0.505375
4                  so2  0.165198
5                pm2_5 -0.248056
6                 pm10 -0.329013
7       gdp_per_capita  0.734343
8             Mean BMI  0.560008
9   che_per_capita_usd  0.110750
10        poverty_rate -0.684580

In [24]:
# correlations: gdp_per_capita has a positive correlation with

'LogisticRegerssion to predict predict categorical data'  'must include confusion_matrix and accuracy score; bonus = classification report'

'RandomForestRegressor to predict continuous data'  'must include accuracy score'

'multiple linear regression: to display correlations between X features and Y (life expectancy)'

'principal component analysis and unsupervised ML; alternative method to find correlations'

'principal component analysis and unsupervised ML; alternative method to find correlations'